name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Build
        run: |
          yarn install
          yarn build
      - uses: peaceiris/actions-gh-pages@v3
        name: Deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
