name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to github pages
        run: |
          yarn install
          git config --global user.email genshin-tracker@jcuneo.com
          git config --global user.name GenshinTracker
          yarn deploy
